#!/bin/bash

set -xe

if ! [[ -d /build/source ]]; then
  rm -rf /build /prefix || :
  cp -rp /deploy/build /
  cp -rp /deploy/prefix /
  cd /build
fi

rsync-update /data/libtorrent/ /build/source/

cd /build/source

if ! [[ -f "./configure" ]]; then
  echo -e "\033[0;32mlibtorrent autogen.sh\033[0m"
  ./autogen.sh
fi

cd /build/output

if ! [[ -f "./config.h" ]]; then
  echo -e "\033[0;32mlibtorrent configure\033[0m"
  . /env.configure
  /build/source/configure --prefix=/prefix --disable-backtrace
fi

make
make install
make check TESTS=
make check
