#!/bin/bash

CONTEXT_NAME="${1:?Missing context name argument.}"
TAG_FULL="${2:?Missing tag full argument.}"

set -e

cat - <<EOF
# Bash profile for rtorrent-docker run containers.

export PATH="\${PATH}:/prefix/bin"

export PROMPT_COMMAND='PS1="<${TAG_FULL}> \\h: \[\e[\$(if [[ \$? != "0" ]]; then echo 31m; elif [[ "\${USER}" = "root" ]]; then echo 32m; else echo 0m; fi)\]\\W\[\e[0m\]>"'
EOF
