#!/bin/sh

set -e

arg_packages="${@}"

rm -rf /var/cache/apk-deploy &> /dev/null || :
mkdir -p /var/cache/apk-deploy

cd /var/cache/apk-stage
find . -type d -exec mkdir -p "/var/cache/apk/{}" \;
find . -type f -exec ln -s "/var/cache/apk-stage/{}" "/var/cache/apk/{}" \;

if apk add --no-network ${arg_packages}; then
  echo "\033[0;32minstalled all packages from cache\033[0m"
  exit 0
fi

if ! apk add ${arg_packages}; then
  echo "\033[0;31mfailed to install some packages from remote repository\033[0m"
  exit 1
fi

echo "\033[0;33minstalled all packages from remote repository\033[0m"

cd /var/cache/apk
find . -type d -exec mkdir -p "/var/cache/apk-deploy/{}" \;
find . -type f -exec mv "{}" "/var/cache/apk-deploy/{}" \;
