#!/bin/bash

set -e

arg_source="${1:?Missing source argument.}"
arg_target="${2:?Missing target argument.}"

mkdir -p "${arg_target}"

rsync -rlpgoD -muc --delete-after \
\
--include '/config.h' \
\
--exclude '*.ac' \
--exclude '*.am' \
--exclude '*.m4' \
--exclude '*.pc.in' \
--exclude '/AUTHORS' \
--exclude '/autogen.sh' \
--exclude '/ChangeLog' \
--exclude '/COPYING' \
--exclude '/INSTALL' \
--exclude '/NEWS' \
--exclude '/README' \
\
--exclude '*.cc' \
--exclude '*.h' \
\
${arg_source} ${arg_target}
