#!/bin/bash

set -e

arg_source="${1:?Missing source argument.}"
arg_target="${2:?Missing target argument.}"

mkdir -p "${arg_target}"

rsync -v -rlpgoD -muc -t --delete-after \
\
--include '*.am' \
--include '*.m4' \
--include '*.pc.in' \
--include '/configure.ac' \
--include '/autogen.sh' \
\
--include '*.cc' \
--include '*.h' \
\
--include '*/' \
--exclude '*' \
\
${arg_source} ${arg_target}
