#!/bin/bash

set -e

arg_source="${1:?Missing source argument.}"
arg_target="${2:?Missing target argument.}"

mkdir -p "${arg_target}"

rsync -rlpgoD -m --update --delete-after --checksum -v \
\
--include '*.ac' \
--include '*.am' \
--include '*.m4' \
--include '*.pc.in' \
--include '/AUTHORS' \
--include '/autogen.sh' \
--include '/ChangeLog' \
--include '/COPYING' \
--include '/INSTALL' \
--include '/NEWS' \
--include '/README' \
\
--include '*.cc' \
--include '*.h' \
\
--include '*/' \
--exclude '*' \
${arg_source} ${arg_target}
