#!/bin/bash

set -e

source_file="${1:?Missing source file argument.}"
target_directory="${1:?Missing target directory argument.}"

while read -r line; do
  file_mtime="${line[0]}"
  file_name="${line[1]}"

  echo touch -m --date "${file_mtime}" "${file_name}"
done < "${source_file}"
