#!/usr/bin/env bash

rdo_header common

rdo__compare_id__file_image() {
  local file_name="${1:?Missing file argument.}"
  local image_name="${2:?Missing image argument.}"

  if ! [[ -f "${file_name}" ]]; then
    return 1
  fi

  local file_id="$(cat "${file_name}")"
  local image_id="$(rdo docker inspect --id "${image_name}")"

  [[ -n "${file_id}" ]] && [[ "${file_id}" == "${image_id}" ]]
}

rdo__image_id() {
  local image_name="${1:?Missing image argument.}"
  echo "$(rdo docker inspect --id "${image_name}")"
}

rdo__latest_image_id__label() {
  local label="${1:?Missing label argument.}"
  local image_id="$(docker images --all --quiet --filter label=${label} | head -n1)"

  if [[ -n "${image_id}" ]]; then
    rdo__image_id "${image_id}"
  fi
}
