#!/usr/bin/env bash

include_header network

rdo_network() {
  # eval "$(args::init_subcommand "rdo network" "Manage networks.")"

  # args::new_command 'clean' empty 'Remove all networks' \
  #                   'rdo_network_clean "${@}"'
  # args::new_command 'ls' default 'List networks' \
  #                   'rdo_network_ls "${@}"'

  # args::new_command 'address' default 'Get network address' \
  #                   'rdo_network_address "${@}"'
  # args::new_command 'bridge' default 'Get bridge name' \
  #                   'rdo_network_bridge "${@}"'
  # args::new_command 'interface-name' default 'Get interface name' \
  #                   'rdo_network_interface_name "${@}"'
  # args::new_command 'prefix' default 'Get network prefix' \
  #                   'rdo_network_prefix "${@}"'
  # args::new_command 'subnet' default 'Get network subnet' \
  #                   'rdo_network_subnet "${@}"'

  # # TODO: Move all iptables stuff into sub-command:
  # args::new_command 'iptables' default 'Call iptables on docker host' \
  #                   'rdo_network_iptables "${@}"'
  # args::new_command 'iptables-flush' empty 'Flush rdo-specific iptables rules on docker host' \
  #                   'rdo_network_iptables_flush'
  # args::new_command 'iptables-list' empty 'List rdo-specific iptables rules on docker host' \
  #                   'rdo_network_iptables_list'
  # args::new_command 'iptables-save' default 'Call iptables-save on docker host' \
  #                   'rdo_network_iptables_save "${@}"'

  # args::new_command 'forward' default 'Add forward rules between networks' \
  #                   'rdo_network_forward "${@}"'
  # args::new_command 'isolate-network' default 'Isolate network' \
  #                   'rdo_network_isolate_network "${@}"'
  # args::new_command 'nat' default 'Add nat rules between networks' \
  #                   'rdo_network_nat "${@}"'

  # args::new_command 'tc' default 'Call tc on docker host' \
  #                   'rdo_network_tc "${@}"'
  # args::new_command 'tc-replace-root-tbf' default 'Replace tc root tbf rule of node' \
  #                   'rdo_network_tc_replace_root_tbf "${@}"'
  # args::new_command 'tc-del-root' default 'Delete root rule of node' \
  #                   'rdo_network_tc_del_root "${@}"'

  # eval "$(args::process)"

  # start of generated bash args 'rdo network'

  while true; do
    case "${1}" in
      --help|-h|'')
        echo "Usage: rdo network"
        echo
        echo "Manage networks."
        echo
        echo "Commands:"
        echo "  clean                 Remove all networks"
        echo "  ls                    List networks"
        echo "  address               Get network address"
        echo "  bridge                Get bridge name"
        echo "  interface-name        Get interface name"
        echo "  prefix                Get network prefix"
        echo "  subnet                Get network subnet"
        echo "  iptables              Call iptables on docker host"
        echo "  iptables-flush        Flush rdo-specific iptables rules on docker host"
        echo "  iptables-list         List rdo-specific iptables rules on docker host"
        echo "  iptables-save         Call iptables-save on docker host"
        echo "  forward               Add forward rules between networks"
        echo "  isolate-network       Isolate network"
        echo "  nat                   Add nat rules between networks"
        echo "  tc                    Call tc on docker host"
        echo "  tc-replace-root-tbf   Replace tc root tbf rule of node"
        echo "  tc-del-root           Delete root rule of node"
        echo
        echo "Run 'rdo network COMMAND --help' for more information on a command."
        exit 0
        ;;
      *)
        if [[ -n "${1}" ]] && [[ -z "${1##-*}" ]]; then
          print_error "${args__root}: unknown flag: ${1}"
          return 1
        fi

        break
        ;;
    esac
  done

  local args__root="rdo network"
  local args__cmd="${1}"
  shift || :

  case "${args__cmd}" in
    clean)
      args::verify_command_empty "${@}"
      rdo_network_clean "${@}"
      ;;
    ls)
      rdo_network_ls "${@}"
      ;;
    address)
      rdo_network_address "${@}"
      ;;
    bridge)
      rdo_network_bridge "${@}"
      ;;
    interface-name)
      rdo_network_interface_name "${@}"
      ;;
    prefix)
      rdo_network_prefix "${@}"
      ;;
    subnet)
      rdo_network_subnet "${@}"
      ;;
    iptables)
      rdo_network_iptables "${@}"
      ;;
    iptables-flush)
      args::verify_command_empty "${@}"
      rdo_network_iptables_flush
      ;;
    iptables-list)
      args::verify_command_empty "${@}"
      rdo_network_iptables_list
      ;;
    iptables-save)
      rdo_network_iptables_save "${@}"
      ;;
    forward)
      rdo_network_forward "${@}"
      ;;
    isolate-network)
      rdo_network_isolate_network "${@}"
      ;;
    nat)
      rdo_network_nat "${@}"
      ;;
    tc)
      rdo_network_tc "${@}"
      ;;
    tc-replace-root-tbf)
      rdo_network_tc_replace_root_tbf "${@}"
      ;;
    tc-del-root)
      rdo_network_tc_del_root "${@}"
      ;;
    *)
      print_error "rdo network: unknown command: ${args__cmd}"
      exit 1
      ;;
  esac

  # end of generated bash args 'rdo network'
}

rdo_network_clean() {
  rdo_network_iptables_flush || true

  local networks
  mapfile -t networks < <(rdo_network_ls --quiet --no-trunc)

  if (( ${#networks[@]} > 0 )); then
    docker network rm "${networks[@]}"
  fi
}

rdo_network_ls() {
  docker network ls --filter "label=project=rdo" "${@}"
}

rdo_network_address() {
  local subnet
  subnet="$(rdo_network_subnet "${@}")"
  echo "${subnet%%/*}"
}

rdo_network_bridge() {
  local name="${1:?Missing name argument.}"
  local network_id
  network_id="$(docker network inspect --format {{.Id}} "${name}")"

  if [[ -z "${network_id:0:12}" ]]; then
    print_error "rdo_network_bridge: could not find network bridge: ${name}"
    exit 1
  fi

  echo "br-${network_id:0:12}"
}

rdo_network_interface_name() {
  # eval "$(args::init_options_string "rdo network interface-name NODE-NAME" "node_name" "Get node's interface name.")"

  # args::new_option "ifname" string "" "Node interface name" 'local ifname="eth0"' 'ifname="${args__1}"'

  # eval "$(args::process)"

  # start of generated bash args 'rdo network interface-name NODE-NAME'

  local ifname="eth0"

  while true; do
    case "${1}" in
      --ifname)
        local args__1="${2:?Missing argument for '${1}'.}"
        shift 2
        ifname="${args__1}"
        ;;
      --help|-h)
        echo "Usage: rdo network interface-name NODE-NAME"
        echo
        echo "Get node's interface name."
        echo
        echo "Options:"
        echo "      --ifname   Node interface name"
        echo
        echo "Run 'rdo network interface-name NODE-NAME COMMAND --help' for more information on a command."
        exit 0
        ;;
      *)
        if [[ -n "${1}" ]] && [[ -z "${1##-*}" ]]; then
          print_error "${args__root}: unknown flag: ${1}"
          return 1
        fi

        break
        ;;
    esac
  done

  if (( ${#} > 1 )); then
    print_error "rdo network interface-name NODE-NAME: too many arguments"
    exit 1
  fi

  if (( ${#} == 0 )) || [[ -z "${1}" ]]; then
    print_error "rdo network interface-name NODE-NAME: missing or empty argument"
    exit 1
  fi

  local node_name="${1}"
  shift

  # end of generated bash args 'rdo network interface-name NODE-NAME'

  local sandbox_key ip_entry
  sandbox_key="$(docker inspect --format '{{ .NetworkSettings.SandboxKey }}' "${node_name}")"
  ip_entry="$(rdo__call_host sudo nsenter --net="${sandbox_key}" -- ip -oneline link show dev "${ifname}")"

  if ! [[ "${ip_entry}" =~ ^[0-9]*:\ [^@\ ]*@if([0-9]*):\ [^$]*$ ]]; then
    exit 1
  fi

  if ! [[ "$(rdo__call_host ip -oneline link show)" =~ [0-9]*:\ ([^@\ ]*)@if$(( BASH_REMATCH[1] - 1 )):\  ]]; then
    exit 1
  fi

  echo "${BASH_REMATCH[1]}"
}

rdo_network_prefix() {
  local subnet
  subnet="$(rdo_network_subnet "${@}")"
  echo "${subnet##*/}"
}

rdo_network_subnet() {
  local name="${1:?Missing name argument.}"
  docker network inspect --format '{{ (index .IPAM.Config 0).Subnet }}' "${name}"
}

rdo_network_iptables() {
  print_normal iptables "${@}"
  rdo__call_host sudo iptables "${@}"
}

rdo_network_iptables_flush() {
  local rules nat_rules filter_rules
  nat_rules="$(rdo_network_iptables_list --table nat | sed -e 's/^-A /sudo iptables --table nat -D /')"
  filter_rules="$(rdo_network_iptables_list --table filter | sed -e 's/^-A /sudo iptables --table filter -D /')"
  rules="$(printf "%s\n%s\n" "${nat_rules}" "${filter_rules}")"

  if [[ -n "${rules}" ]]; then
    rdo__call_host bash -c "echo '${rules}'; ${rules}"
  fi
}

rdo_network_iptables_list() {
  rdo__call_host sudo iptables-save "${@}" | sed -n -e '/ -m comment --comment "rdo network/p'
}

rdo_network_iptables_save() {
  rdo__call_host sudo iptables-save "${@}"
}

rdo_network_forward() {
  eval "$(args::init_options_string "rdo network forward OUTER-NETWORK" "outer_network" "Add FORWARD route between networks.")"

  args::new_option "network" req_string "n" "Add inner network" 'local inner_networks=()' 'inner_networks+=("${args__1}")'

  eval "$(args::process)"

  if (( ${#inner_networks[@]} == 0 )); then
    print_error "rdo network nat: Missing inner networks."
    return 1
  fi

  local outer_network_bridge
  outer_network_bridge="$(rdo_network_bridge "${outer_network}")"

  local inner_network
  for inner_network in "${inner_networks[@]}"; do
    local inner_network_bridge
    inner_network_bridge="$(rdo_network_bridge "${inner_network}")"

    local default_iptables_args=(
      -m comment
      --comment "'rdo network forward ${inner_network}->${outer_network}'"
    )

    rdo_network_iptables "${default_iptables_args[@]}" -t filter -I DOCKER-USER -i "${outer_network_bridge}" -o "${inner_network_bridge}" -j ACCEPT
    rdo_network_iptables "${default_iptables_args[@]}" -t filter -I DOCKER-USER -i "${inner_network_bridge}" -o "${outer_network_bridge}" -j ACCEPT
  done
}

rdo_network_isolate_network() {
  # eval "$(args::init_options_string "rdo network isolate-network NETWORK" "network" "Isolate network.")"

  # eval "$(args::process)"

  # start of generated bash args 'rdo network isolate-network NETWORK'

  while true; do
    case "${1}" in
      --help|-h)
        echo "Usage: rdo network isolate-network NETWORK"
        echo
        echo "Isolate network."
        echo
        echo "Run 'rdo network isolate-network NETWORK COMMAND --help' for more information on a command."
        exit 0
        ;;
      *)
        if [[ -n "${1}" ]] && [[ -z "${1##-*}" ]]; then
          print_error "${args__root}: unknown flag: ${1}"
          return 1
        fi

        break
        ;;
    esac
  done

  if (( ${#} > 1 )); then
    print_error "rdo network isolate-network NETWORK: too many arguments"
    exit 1
  fi

  if (( ${#} == 0 )) || [[ -z "${1}" ]]; then
    print_error "rdo network isolate-network NETWORK: missing or empty argument"
    exit 1
  fi

  local network="${1}"
  shift

  # end of generated bash args 'rdo network isolate-network NETWORK'

  local network_bridge
  network_bridge="$(rdo_network_bridge "${network}")"

  local default_iptables_args=(
    -m comment
    --comment "'rdo network isolate-network ${network}'"
  )

  rdo_network_iptables "${default_iptables_args[@]}" -t filter -I DOCKER-USER -i "${network_bridge}" ! -o "${network_bridge}" -j DROP
}

rdo_network_nat() {
  # eval "$(args::init_options_empty "rdo network nat" "Add NAT route.")"

  # args::new_option "bridge" string "" "Use bridge egress" 'local bridge_name' 'bridge_name="${args__1}"'
  # args::new_option "network" req_string "" "Add inner network" 'local inner_networks=()' 'inner_networks+=("${args__1}")'

  # eval "$(args::process)"

  # start of generated bash args 'rdo network nat'

  local bridge_name
  local inner_networks=()
  local args__opt_value__network=

  while true; do
    case "${1}" in
      --bridge)
        local args__1="${2:?Missing argument for '${1}'.}"
        shift 2
        bridge_name="${args__1}"
        ;;
      --network)
        local args__1="${2:?Missing argument for '${1}'.}"
        local args__opt_value__network="${args__1}"
        shift 2
        inner_networks+=("${args__1}")
        ;;
      --help|-h)
        echo "Usage: rdo network nat"
        echo
        echo "Add NAT route."
        echo
        echo "Options:"
        echo "      --bridge    Use bridge egress"
        echo "      --network   Add inner network"
        echo
        echo "Run 'rdo network nat COMMAND --help' for more information on a command."
        exit 0
        ;;
      *)
        if [[ -n "${1}" ]] && [[ -z "${1##-*}" ]]; then
          print_error "${args__root}: unknown flag: ${1}"
          return 1
        fi

        break
        ;;
    esac
  done

  if [[ -z "${args__opt_value__network}" ]]; then
    print_error "${args__root}: missing required flag: --network"
    return 1
  fi

  if (( ${#} > 0 )); then
    print_error "rdo network nat: too many arguments"
    exit 1
  fi

  # end of generated bash args 'rdo network nat'

  local egress_ifname
  local egress_iflink
  local comment

  if [[ -n "${bridge_name}" ]]; then
    egress_ifname="$(rdo_network_bridge "${bridge_name}")"
    egress_iflink="${bridge_name}"
  else
    print_error "rdo network nat: missing egress type"
    exit 1
  fi

  if (( ${#inner_networks[@]} == 0 )); then
    print_error "rdo network nat: Missing inner networks."
    return 1
  fi

  local egress_ipaddr_list=()
  mapfile -t egress_ipaddr_list < <(rdo__call_host ip -4 addr show dev "${egress_ifname}"| sed -ne 's|.*inet \([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*/[0-9]*\).*|\1|p')

  if ! [[ "${egress_ipaddr_list[-1]}" =~ ([0-9]*\.[0-9]*\.[0-9]*)\.([0-9]*)\/([0-9]*) ]]; then
    print_error "rdo network nat: egress interface '${egress_ifname}' does not have any addresses"
    return 1
  fi

  local egress_ipaddr
  local egress_prefix="${BASH_REMATCH[3]}"

  if (( BASH_REMATCH[2] < 200 )); then
    egress_ipaddr="${BASH_REMATCH[1]}.$(( 200 ))"
  else
    egress_ipaddr="${BASH_REMATCH[1]}.$(( BASH_REMATCH[2] + 1 ))"
  fi

  rdo__call_host sudo ip addr add "${egress_ipaddr}/${egress_prefix}" scope global dev "${egress_ifname}"

  local inner_network
  for inner_network in "${inner_networks[@]}"; do
    local inner_network_bridge
    local inner_network_index
    inner_network_bridge="$(rdo_network_bridge "${inner_network}")"
    inner_network_index="$(cat "./run/current/networks/${inner_network}"/index)"

    comment="rdo network nat ${inner_network}->${egress_iflink}(${egress_ifname}:${egress_ipaddr})"

    local mark=$(( 0x30000 + inner_network_index ))
    local default_iptables_args=(
      -m comment
      --comment "'${comment}'"
    )

    # rdo_network_iptables "${default_iptables_args[@]}" -t nat -I POSTROUTING -m mark --mark "${mark}" -o "${egress_ifname}" -j MASQUERADE
    rdo_network_iptables "${default_iptables_args[@]}" -t nat -I POSTROUTING -m mark --mark "${mark}" -o "${egress_ifname}" -j SNAT --to-source "${egress_ipaddr}"

    rdo_network_iptables "${default_iptables_args[@]}" -t filter -I DOCKER-USER -i "${inner_network_bridge}" -o "${egress_ifname}" -j ACCEPT
    rdo_network_iptables "${default_iptables_args[@]}" -t filter -I DOCKER-USER -i "${egress_ifname}" -o "${inner_network_bridge}" -m state --state RELATED,ESTABLISHED -j ACCEPT
    rdo_network_iptables "${default_iptables_args[@]}" -t filter -I DOCKER-USER -i "${inner_network_bridge}" -o "${egress_ifname}" -j MARK --set-mark "${mark}"
  done
}

rdo_network_tc() {
  rdo__call_host sudo tc "${@}"
}

rdo_network_tc_replace_root_tbf() {
  # eval "$(args::init_options_default "rdo network tc-replace-root-tbf [NODE-NAME]..." "Replace tc root tbf rule of nodes.")"

  # # Using rate < 8kbit kills docker containers.
  # args::new_option "rate" req_string "" "Limit ingress traffic rate" \
  #                  'local rate' 'rate="${args__1}"'

  # # TODO: TC and handshakes seem to cause issues with 8kbit.
  # args::new_option "rate-epsilon" empty "" "Limit ingress traffic rate to lowest possible (200kbit)" \
  #                  'local rate' 'rate=200kbit; args__opt_value__rate=200kbit'

  # eval "$(args::process)"

  # start of generated bash args 'rdo network tc-replace-root-tbf [NODE-NAME]...'

  local rate
  local rate
  local args__opt_value__rate=

  while true; do
    case "${1}" in
      --rate)
        local args__1="${2:?Missing argument for '${1}'.}"
        local args__opt_value__rate="${args__1}"
        shift 2
        rate="${args__1}"
        ;;
      --rate-epsilon)
        shift
        rate=200kbit; args__opt_value__rate=200kbit
        ;;
      --help|-h)
        echo "Usage: rdo network tc-replace-root-tbf [NODE-NAME]..."
        echo
        echo "Replace tc root tbf rule of nodes."
        echo
        echo "Options:"
        echo "      --rate           Limit ingress traffic rate"
        echo "      --rate-epsilon   Limit ingress traffic rate to lowest possible (200kbit)"
        echo
        echo "Run 'rdo network tc-replace-root-tbf [NODE-NAME]... COMMAND --help' for more information on a command."
        exit 0
        ;;
      *)
        if [[ -n "${1}" ]] && [[ -z "${1##-*}" ]]; then
          print_error "${args__root}: unknown flag: ${1}"
          return 1
        fi

        break
        ;;
    esac
  done

  if [[ -z "${args__opt_value__rate}" ]]; then
    print_error "${args__root}: missing required flag: --rate"
    return 1
  fi

  # end of generated bash args 'rdo network tc-replace-root-tbf [NODE-NAME]...'

  local commands

  local node_name
  for node_name in "${@}"; do
    local node_ifname
    node_ifname="$(rdo_network_interface_name "${node_name}")"

    tc_command=(
      tc qdisc replace dev "'${node_ifname}'"
      root tbf
      rate "'${rate}'"
      latency 50ms

      # burst 1540 # causes(?) eh_no_peer_info when using NAT (tests/ci-throttle 9a0bd9c078381892f11c662a1f52a83855223334)
      burst 1540
    )

    commands+="$(echo "echo 'tc_replace_root_tbf/${node_name}/${node_ifname}/rate:${rate}' && ${tc_command[@]} && ")"
  done

  rdo__call_host sudo bash -c "\"${commands} : \""
}

rdo_network_tc_del_root() {
  # eval "$(args::init_options_default "rdo network tc-del-root [NODE-NAME]..." "Delete root rule of nodes.")"

  # eval "$(args::process)"

  # start of generated bash args 'rdo network tc-del-root [NODE-NAME]...'

  while true; do
    case "${1}" in
      --help|-h)
        echo "Usage: rdo network tc-del-root [NODE-NAME]..."
        echo
        echo "Delete root rule of nodes."
        echo
        echo "Run 'rdo network tc-del-root [NODE-NAME]... COMMAND --help' for more information on a command."
        exit 0
        ;;
      *)
        if [[ -n "${1}" ]] && [[ -z "${1##-*}" ]]; then
          print_error "${args__root}: unknown flag: ${1}"
          return 1
        fi

        break
        ;;
    esac
  done

  # end of generated bash args 'rdo network tc-del-root [NODE-NAME]...'

  local commands

  local node_name
  for node_name in "${@}"; do
    local node_ifname
    node_ifname="$(rdo_network_interface_name "${node_name}")"

    tc_command=(
      tc qdisc del dev "'${node_ifname}'"
      root
    )

    commands+="$(echo "echo 'tc_del_root/${node_name}/${node_ifname}' && ${tc_command[@]} && ")"
  done

  rdo__call_host sudo bash -c "\"${commands} : \""
}
