#!/usr/bin/env bash

include_header torrent

rdo_torrent() {
  eval "$(args::init_subcommand "rdo torrent" "Manage torrents.")"

  args::new_command "create" default "Create a torrent" \
                    'time rdo_torrent_create "${@}"'

  eval "$(args::process)"
}

rdo_torrent_create() {
  rdo_torrent__init

  eval "$(args::init_options_string "rdo torrent create NAME" "name" "Create a torrent.")"

  # args::new_option "dddd" string "d" "desc" \
  #                  'networks+=("${args__1}")'

  eval "$(args::process)"

  local self_path="./run/torrents/${name}"

  # TODO: Don't recreate.

  rm -rf "${self_path}"{,.torrent}
  mkdir -p "${self_path}"

  rdo_torrent__create_random_file "${self_path}/file"

  local create_args=(
    -a "http://example.com:1234/announce.php"
    -n "${name}"
    -o "/torrents/${name}.torrent"
  )

  create_args+=("/torrents/${name}")

  docker exec -t "rdo-utils-mktorrent" mktorrent "${create_args[@]}"
}

# Helper methods:

rdo_torrent__init() {
  if [[ -n "$(rdo__running_container_id__name "rdo-utils-mktorrent")" ]]; then
    return
  fi

  if [[ -n "$(rdo__container_id__name "rdo-utils-mktorrent")" ]]; then
    docker rm "rdo-utils-mktorrent"
  fi

  rdo_docker context build --empty --cache --no-rebuild --ancestor-project "utils" "run/mktorrent:global"

  mkdir -p "./run/torrents"

  docker run \
         --name "rdo-utils-mktorrent" \
         --rm \
         --detach \
         --network none \
         --mount "type=bind,src=$(project_absolute_unix_path)/run/torrents/,dst=/torrents" \
         "rdo/run/mktorrent:global"
}

rdo_torrent__create_random_file() {
  local filename="${1:?Missing filename argument.}"

  head -c "$(( 5 * 1024 * 1024 ))" < <(head -c 8000 /dev/urandom; while true; do cat "${filename}"; done) > "${filename}"
}
