#!/usr/bin/env bash

include_header torrent

rdo_torrent() {
  eval "$(args::init_subcommand "rdo torrent" "Manage staging of environments.")"

  args::new_command "create" default "Create a torrent" \
                    'rdo_torrent_create'

  eval "$(args::process)"
}

rdo_torrent_create() {
  rdo_torrent__init
}

# Helper methods:

rdo_torrent__init() {
  rdo docker context build --empty --cache --no-rebuild --ancestor-project "utils" "run/mktorrent:global"
}
