#!/bin/bash

cat - <<EOF
set -x

echo 0 > /proc/sys/kernel/yama/ptrace_scope

tmux new -s rdo '
  lldb \
    --one-line "settings set target.disable-aslr false" \
    --one-line run \
    --one-line-on-crash "thread backtrace all" \
    --file "rtorrent" \
    -- -o "system.daemon.set=true,import=/run/self/rc"
'

EOF
