#!/bin/bash

set -e

local TESTS=(
  ci-default
  ci-low-diskspace
  ci-nat
  ci-throttle
  ci-torrents
)

local SUCCESSFUL_TESTS=()
local FAILED_TESTS=()

local test_name
for test_name in "${TESTS[@]}"; do
  print_progress
  print_progress "running test: ${test_name}"
  print_progress

  if ./rdo batch "./tests/${test_name}"; then
    print_progress
    print_progress "*** SUCCEEDED ***"
    print_progress

    SUCCESSFUL_TESTS+=("${test_name}")
  else
    print_error
    print_error "*** FAILED ***"
    print_error

    FAILED_TESTS+=("${test_name}")
  fi
done

print_progress "CI results:"
print_progress

for t in "${SUCCESSFUL_TESTS[@]}"; do
  print_progress "succeeded: ${t}"
done

for t in "${FAILED_TESTS[@]}"; do
  print_error "failed:    ${t}"
done

print_progress

rdo_stage_clean

if (( ${#FAILED_TESTS[@]} != 0 )); then
  return 1
fi
