#!/bin/bash

#
# Missing tests:
#

rdo_test_begin


#
# Topology, trackers and torrents:
#

rdo_stage_network "rt-global"

rdo_stage_dns     --run-template "dns-default"     --network "rt-global" "rt-dns-global"
rdo_stage_tracker --run-template "tracker-default" --network "rt-global" "rt-tracker-global"

rdo_stage_deploy

default_client_args=(
  --run-template "rt-default"
  --network "rt-global"
  --dns-inet "rt-dns-global:rt-global"
)

#
# Seeders:
#

rdo_stage_rtorrent "${default_client_args[@]}" "rt-seed-global"

for i in {1..3}; do
  rdo_torrent_create --domain "rt-tracker-global.rt" --size-mb "1" "torrent-${i}"
  rdo_torrent_node   --seeder "rt-seed-global" "torrent-${i}"
done

rdo_stage_deploy
rdo_torrent_wait --print --wait-all \
                 $(printf -- " --seeding rt-seed-global:torrent-%s" {1..3})


#
# Test throttle:
#

test_clients=(
  "rt-choke-group-default-2t-complete-both"
  "rt-choke-group-default-2t-starve-both"
  "rt-choke-group-default-2t-starve-one"
)

test_tc_rate_800k+=(
  "rt-choke-group-default-2t-starve-both"
)
test_tc_rate_1200k+=(
  "rt-choke-group-default-2t-starve-one"
)
test_tc_rate_1600k+=(
  "rt-choke-group-default-2t-complete-both"
)

test_torrent_results+=(
  --completed     "rt-choke-group-default-2t-complete-both:torrent-1"
  --completed     "rt-choke-group-default-2t-complete-both:torrent-2"
  --not-completed "rt-choke-group-default-2t-starve-both:torrent-1"
  --not-completed "rt-choke-group-default-2t-starve-both:torrent-2"

  # --one-completed "rt-choke-group-default-2t-starve-one:torrent-1+torrent-2"

  # --one-completed "rt-choke-group-default-2t-complete-both:torrent-1+torrent-2"
  # --one-completed "rt-choke-group-default-2t-starve-both:torrent-1+torrent-2"
)

rdo_stage_rtorrent "${default_client_args[@]}" "${test_clients[@]}"

rdo_network_tc_replace_root_tbf --rate-epsilon "${test_clients[@]}"

rdo_stage_append_rc \
  $(printf -- " --node %s" "${test_clients[@]}") \
  '# CI-specific logging:
log.open_file = "ci", /run/self/logs/ci.log
log.add_output = "torrent_info", "ci"
log.add_output = "protocol_piece_events", "ci"'

rdo_stage_append_rc \
  $(printf -- " --node %s" "${test_clients[@]}") \
  'schedule2 = update_choke_queue_balance,1,1,((choke_group.all.down.update_balance))'

# Prioritize only one torrent:
rdo_stage_append_rc \
  --node "rt-choke-group-default-2t-starve-both" \
  --node "rt-choke-group-default-2t-starve-one" \
  --node "rt-choke-group-default-2t-complete-both" \
  'method.set_key = event.download.inserted,starve_torrent_2, {(branch,((equal,(d.name),"torrent-2")),((d.priority.set,0)))}'

rdo_torrent_node $(printf -- " --leecher %s" "${test_clients[@]}") "torrent-1"
rdo_torrent_node $(printf -- " --leecher %s" "${test_clients[@]}") "torrent-2"

rdo_stage_deploy
rdo_torrent_wait --print --wait-all \
                 $(printf -- " --hash-done %s:torrent-1" "${test_clients[@]}") \
                 $(printf -- " --hash-done %s:torrent-2" "${test_clients[@]}")

rdo_network_tc_replace_root_tbf --rate 800kbit  "${test_tc_rate_800k[@]}"
rdo_network_tc_replace_root_tbf --rate 1200kbit "${test_tc_rate_1200k[@]}"
rdo_network_tc_replace_root_tbf --rate 1600kbit "${test_tc_rate_1600k[@]}"

rdo_torrent_wait --print --wait-all "${test_torrent_results[@]}"

rdo_test_end
