#!/bin/bash

#
# Test default behavior of rtorrent in various network setttings.
#

# TODO: This test should be removed, and replace with specific test for what is done here.
# TODO: Add test for various download state events.

rdo_test_begin


#
# Topology, trackers and torrents:
#

# TODO: Add test for both v4only and v6only seeders.

rdo_stage_network                "rt-global-seed"
rdo_stage_network --disable-ipv6 "rt-global-v4"
rdo_stage_network --disable-ipv4 "rt-global-v6"
rdo_stage_network --disable-ipv6 "rt-global-v4-isolate"
rdo_stage_network --disable-ipv4 "rt-global-v6-isolate"

rdo_network_forward --bridge "rt-global-seed" --ingress-ipv4 "rt-global-v4"
rdo_network_forward --bridge "rt-global-seed" --ingress-ipv6 "rt-global-v6"

rdo_stage_dns     --run-template "dns-default"     --network "rt-global-seed" "rt-dns-global"
rdo_stage_tracker --run-template "tracker-default" --network "rt-global-seed" "rt-tracker-global"

rdo_stage_deploy


################ Multi-file torrents!!! ################


#
# Seeders:
#

# rdo_stage_rtorrent \
#   --run-template "rt-default" \
#   --dns-inet "rt-dns-global:rt-global-seed" \
#   --network "rt-global-seed" \
#   "rt-seed-global"

# We need to force leechers to announce using ipv4, this needs to be fixed so clients prefer ipv4 when available.

rdo_stage_rtorrent \
  --run-template "rt-default" \
  --dns-inet "rt-dns-global:rt-global-seed" \
  --network "rt-global-v4" \
  "rt-seed-global-v4"

rdo_stage_append_rc \
  --node "rt-seed-global-v4" \
  'network.block.ipv6.set = true'


# Due to trackers not properly supporting both ipv4 and ipv6 properly,
# we need two seeders.
#
# FIXME: This should be in global-seed network, however we use v6 to force tracker to use ipv6.
# rdo_stage_rtorrent \
#
# Fix opentracker compile, upgrade alpine, use ipv4in6 with one tracker, add separate tests for ipv6-only tracker.
#
#   --run-template "rt-default" \
#   --dns-inet6 "rt-dns-global:rt-global-seed" \
#   --network "rt-global-seed" \
#   "rt-seed-global-v6"

rdo_stage_rtorrent \
  --run-template "rt-default" \
  --dns-inet6 "rt-dns-global:rt-global-seed" \
  --network "rt-global-v6" \
  "rt-seed-global-v6"

rdo_stage_append_rc \
  --node "rt-seed-global-v6" \
  'network.block.ipv4.set = true'

#  'network.prefer.ipv6.set = true'

rdo_stage_append_rc \
  --node "rt-seed-global-v6" \
  'network.block.ipv4in6.set = true'


rdo_torrent_create --domain "rt-tracker-global.rt" "torrent-global"
rdo_torrent_node   --seeder "rt-seed-global-v4"    "torrent-global"
rdo_torrent_node   --seeder "rt-seed-global-v6"    "torrent-global"

# Fix v4/6only isolation/seeders/whatever.
rdo_torrent_create --domain "rt-tracker-global.rt" "torrent-global-v4only"
rdo_torrent_node   --seeder "rt-seed-global-v4"    "torrent-global-v4only"

rdo_torrent_create --domain "rt-tracker-global.rt" "torrent-global-v6only"
rdo_torrent_node   --seeder "rt-seed-global-v6"    "torrent-global-v6only"

rdo_torrent_create --domain "udp:rt-tracker-global.rt" "torrent-global-udp"
rdo_torrent_node   --seeder "rt-seed-global-v4"        "torrent-global-udp"
rdo_torrent_node   --seeder "rt-seed-global-v6"        "torrent-global-udp"

rdo_stage_deploy
rdo_torrent_wait --print --wait-all \
                 \
                 --hash-done     "rt-seed-global-v4:torrent-global" \
                 --seeding       "rt-seed-global-v4:torrent-global" \
                 \
                 --hash-done     "rt-seed-global-v6:torrent-global" \
                 --seeding       "rt-seed-global-v6:torrent-global" \
                 \
                 --hash-done     "rt-seed-global-v4:torrent-global-v4only" \
                 --seeding       "rt-seed-global-v4:torrent-global-v4only" \
                 \
                 --hash-done     "rt-seed-global-v6:torrent-global-v6only" \
                 --seeding       "rt-seed-global-v6:torrent-global-v6only" \
                 \
                 --hash-done     "rt-seed-global-v4:torrent-global-udp" \
                 --seeding       "rt-seed-global-v4:torrent-global-udp" \
                 \
                 --hash-done     "rt-seed-global-v6:torrent-global-udp" \
                 --seeding       "rt-seed-global-v6:torrent-global-udp"


#
# Leechers:
#

connected_clients=(
  "rt-connected-global-v4v6"
  "rt-connected-globalv4-v4v6"
  "rt-connected-globalv4-v4only"
  "rt-connected-globalv6-v4v6"
  "rt-connected-globalv6-v6only"
)

connected_v4_clients=(
  "rt-connected-global-v4v6"
  "rt-connected-globalv4-v4v6"
  "rt-connected-globalv4-v4only"
)

connected_v4only_clients=()
connected_v6only_clients=()

blocked_v6only_clients=()
blocked_v4only_clients=()

v4_rtorrent_args=(
  --run-template "rt-default"
  --dns-inet "rt-dns-global:rt-global-seed"
)

v6_rtorrent_args=(
  --run-template "rt-default"
  --dns-inet6 "rt-dns-global:rt-global-seed"
)

rdo_stage_rtorrent "${v4_rtorrent_args[@]}" \
  --network "rt-global-seed" \
  "rt-connected-global-v4v6"

rdo_stage_rtorrent "${v4_rtorrent_args[@]}" \
  --network "rt-global-v4" \
  "rt-connected-globalv4-v4v6" \
  "rt-connected-globalv4-v4only"

rdo_stage_rtorrent "${v6_rtorrent_args[@]}" \
  --network "rt-global-v6" \
  "rt-connected-globalv6-v4v6" \
  "rt-connected-globalv6-v6only"

rdo_stage_append_rc \
  --node "rt-connected-globalv6-v6only" \
  'network.block.ipv4.set = true'

rdo_stage_append_rc \
  --node "rt-connected-globalv4-v4only" \
  'network.block.ipv6.set = true'


#
# Block ipv4/6 tests:
#

# TODO: Test numeric tracker urls.

# TODO: Add option to block http tracker requests?

connected_v4only_clients+=(
  "rt-blocked-global-v4only"
)

connected_v6only_clients+=(
  "rt-blocked-global-v6only"
)

blocked_v4only_clients+=(
  "rt-blocked-global-v6only"
  "rt-blocked-globalv4-v6only"
  "rt-blocked-globalv6-v4only"
)

blocked_v6only_clients+=(
  "rt-blocked-global-v4only"
  "rt-blocked-globalv6-v4only"
  "rt-blocked-globalv4-v6only"
)

rdo_stage_rtorrent "${v4_rtorrent_args[@]}" \
  --network "rt-global-seed" \
  "rt-blocked-global-v4only" \
  "rt-blocked-global-v6only"

rdo_stage_rtorrent "${v4_rtorrent_args[@]}" \
  --network "rt-global-v4-isolate" \
  "rt-blocked-globalv4-v6only"

rdo_stage_rtorrent "${v6_rtorrent_args[@]}" \
  --network "rt-global-v6-isolate" \
  "rt-blocked-globalv6-v4only"

rdo_stage_append_rc \
  --node "rt-blocked-global-v6only" \
  --node "rt-blocked-globalv4-v6only" \
  'network.block.ipv4.set = true'

rdo_stage_append_rc \
  --node "rt-blocked-global-v4only" \
  --node "rt-blocked-globalv6-v4only" \
  'network.block.ipv6.set = true'

# TODO: Also test 'prefer-ipv6.

#
# Bind/Local address tests:
#

# connected_v4_clients+=(
# )

# rdo_stage_rtorrent "${v4_rtorrent_args[@]}" \
#   --network "rt-global-seed" \
#   "rt-bind-address-v4" \

# # Add to blocked global

# rdo_stage_append_rc \
#   --node "rt-bind-address-v4" \
#   'network.bind_address.set = 1.2.3.4'

# rdo_stage_append_rc \
#   --node "rt-unknown-bind-address-v6" \
#   'network.bind_address.set = 2001:aaaa:bbbb::aaaa:bbbb'

# rdo_stage_append_rc \
#   --node "rt-unknown-local-address-v4" \
#   'network.local_address.set = 1.2.3.4'

# rdo_stage_append_rc \
#   --node "rt-unknown-local-address-v4" \
#   'network.local_address.set = 2001:aaaa:bbbb::aaaa:bbbb'


#
# Default options:
#

rdo_stage_append_rc \
  $(printf -- " --node %s" "${connected_clients[@]}") \
  $(printf -- " --node %s" "${connected_v4_clients[@]}") \
  $(printf -- " --node %s" "${connected_v4only_clients[@]}") \
  $(printf -- " --node %s" "${connected_v6only_clients[@]}") \
  $(printf -- " --node %s" "${blocked_v4only_clients[@]}") \
  $(printf -- " --node %s" "${blocked_v6only_clients[@]}") \
  'protocol.pex.set = false'

#
# Add torrents:
#

rdo_torrent_node \
  $(printf -- " --leecher %s" "${connected_clients[@]}") \
  "torrent-global"

rdo_torrent_node \
  $(printf -- " --leecher %s" "${connected_clients[@]}") \
  "torrent-global-udp"

rdo_torrent_node \
  $(printf -- " --leecher %s" "${connected_v4only_clients[@]}") \
  $(printf -- " --leecher %s" "${blocked_v4only_clients[@]}") \
  "torrent-global-v4only"

rdo_torrent_node \
  $(printf -- " --leecher %s" "${connected_v6only_clients[@]}") \
  $(printf -- " --leecher %s" "${blocked_v6only_clients[@]}") \
  "torrent-global-v6only"

# TODO: Fix udp6 trackers.

rdo_stage_deploy
rdo_torrent_wait --print --wait-all \
                 \
                 $(printf -- " --hash-done %s:torrent-global" "${connected_clients[@]}") \
                 $(printf -- " --not-seeding %s:torrent-global" "${connected_clients[@]}") \
                 $(printf -- " --completed %s:torrent-global" "${connected_clients[@]}") \
                 \
                 $(printf -- " --hash-done %s:torrent-global-udp" "${connected_v4_clients[@]}") \
                 $(printf -- " --not-seeding %s:torrent-global-udp" "${connected_v4_clients[@]}") \
                 $(printf -- " --completed %s:torrent-global-udp" "${connected_v4_clients[@]}") \
                 \
                 $(printf -- " --hash-done %s:torrent-global-v4only" "${connected_v4only_clients[@]}") \
                 $(printf -- " --not-seeding %s:torrent-global-v4only" "${connected_v4only_clients[@]}") \
                 $(printf -- " --completed %s:torrent-global-v4only" "${connected_v4only_clients[@]}") \
                 \
                 $(printf -- " --hash-done %s:torrent-global-v6only" "${connected_v6only_clients[@]}") \
                 $(printf -- " --not-seeding %s:torrent-global-v6only" "${connected_v6only_clients[@]}") \
                 $(printf -- " --completed %s:torrent-global-v6only" "${connected_v6only_clients[@]}") \
                 \
                 $(printf -- " --hash-done %s:torrent-global-v4only" "${blocked_v4only_clients[@]}") \
                 $(printf -- " --not-seeding %s:torrent-global-v4only" "${blocked_v4only_clients[@]}") \
                 $(printf -- " --not-completed %s:torrent-global-v4only" "${blocked_v4only_clients[@]}") \
                 \
                 $(printf -- " --hash-done %s:torrent-global-v6only" "${blocked_v6only_clients[@]}") \
                 $(printf -- " --not-seeding %s:torrent-global-v6only" "${blocked_v6only_clients[@]}") \
                 $(printf -- " --not-completed %s:torrent-global-v6only" "${blocked_v6only_clients[@]}")

rdo_test_end
