#!/bin/bash

#
# Test default behavior of rtorrent in various network setttings.
#

# TODO: This test should be removed, and replace with specific test for what is done here.
# TODO: Add test for various download state events.

rdo_test_begin


#
# Topology, trackers and torrents:
#

# TODO: Add test for both v4only and v6only seeders.

rdo_stage_network               "rt-global-v4"
rdo_stage_network --enable-ipv6 "rt-global-v4v6"

rdo_stage_dns     --run-template "dns-default"     --network "rt-global-v4v6" "rt-dns-global"
rdo_stage_tracker --run-template "tracker-default" --network "rt-global-v4v6" "rt-tracker-global"

rdo_stage_deploy

default_rtorrent_args=(
  --run-template "rt-default"
  --dns-inet "rt-dns-global:rt-global-v4v6"
)


#
# Seeders:
#

rdo_stage_rtorrent \
  "${default_rtorrent_args[@]}" \
  --network "rt-global-v4v6" \
  "rt-seed-global"

rdo_torrent_create --domain "rt-tracker-global.rt" "torrent-global"
rdo_torrent_node   --seeder "rt-seed-global" "torrent-global"

rdo_stage_deploy
rdo_torrent_wait --print --wait-all \
                 \
                 --hash-done     "rt-seed-global:torrent-global" \
                 --seeding       "rt-seed-global:torrent-global"


#
# Leechers:
#

test_clients=(
  "rt-leech-global"
)

rdo_stage_rtorrent "${default_rtorrent_args[@]}" --network "rt-global-v4v6" "rt-leech-global"

rdo_torrent_node $(printf -- " --leecher %s" "${test_clients[@]}") "torrent-global"

rdo_stage_deploy
rdo_torrent_wait --print --wait-all \
                 \
                 --hash-done     "rt-leech-global:torrent-global" \
                 --not-seeding   "rt-leech-global:torrent-global" \
                 --completed     "rt-leech-global:torrent-global"

rdo_test_end
