#!/bin/bash

#
# Test rtorrent with NAT.
#

rdo_test_begin


#
# Topology, trackers and torrents:
#

rdo_stage_network --disable-ipv6 "rt-global-v4"

rdo_stage_network "rt-nat-1"
rdo_network_nat   --network "rt-nat-1" --bridge "rt-global-v4"

rdo_stage_network "rt-nat-2"
rdo_network_nat   --network "rt-nat-2" --bridge "rt-global-v4"

rdo_stage_network "rt-nat-3"
rdo_network_nat   --network "rt-nat-3" --bridge "rt-global-v4"

rdo_stage_dns     --run-template "dns-default"     --network "rt-global-v4" "rt-dns-global"
rdo_stage_tracker --run-template "tracker-default" --network "rt-global-v4" "rt-tracker-global"

rdo_stage_deploy

default_rtorrent_args=(
  --run-template "rt-default"
  --dns-inet "rt-dns-global:rt-global-v4"
)


#
# Seeders:
#

rdo_stage_rtorrent \
  "${default_rtorrent_args[@]}" \
  --network "rt-global-v4" \
  "rt-seed-global"

rdo_torrent_create --domain "rt-tracker-global.rt" "torrent-global"
rdo_torrent_node   --seeder "rt-seed-global" "torrent-global"

rdo_stage_deploy
rdo_torrent_wait --print --wait-all \
                 \
                 --hash-done     "rt-seed-global:torrent-global" \
                 --seeding       "rt-seed-global:torrent-global"


#
# Leechers:
#

test_clients=(
  "rt-leech-nat-1-1"
  "rt-leech-nat-2-1"
  "rt-leech-nat-3-"{1..4}
)

rdo_stage_rtorrent "${default_rtorrent_args[@]}" --network "rt-nat-1" "rt-leech-nat-1-1"
rdo_stage_rtorrent "${default_rtorrent_args[@]}" --network "rt-nat-2" "rt-leech-nat-2-1"
rdo_stage_rtorrent "${default_rtorrent_args[@]}" --network "rt-nat-3" "rt-leech-nat-3-"{1..4}

rdo_torrent_node $(printf -- " --leecher %s" "${test_clients[@]}") "torrent-global"

rdo_stage_deploy
rdo_torrent_wait --print --wait-all \
                 $(printf -- " --completed %s:torrent-global" "${test_clients[@]}")

rdo_test_end
