#!/bin/bash

#
# Test default behavior of rtorrent in various network setttings.
#

rdo_test_begin


#
# Topology, trackers and torrents:
#

rdo_stage_network "rt-global"

rdo_stage_dns     --run-template "dns-default"     --network "rt-global" "rt-dns-global"
rdo_stage_tracker --run-template "tracker-default" --network "rt-global" "rt-tracker-global"

rdo_stage_deploy

default_client_args=(
  --run-template "rt-default"
  --network "rt-global"
  --dns-inet "rt-dns-global:rt-global"
)


#
# Seeders:
#

rdo_stage_rtorrent "${default_client_args[@]}" "rt-seed-global"

rdo_torrent_create --domain "rt-tracker-global.rt" --size-kb "100" "torrent-100k"
rdo_torrent_create --domain "rt-tracker-global.rt" --size-kb "500" "torrent-500k"
rdo_torrent_node --seed --node "rt-seed-global" "torrent-100k"
rdo_torrent_node --seed --node "rt-seed-global" "torrent-500k"

rdo_stage_deploy
rdo_torrent_wait --print --wait-all \
                 \
                 --hash-done     "rt-seed-global:torrent-100k" \
                 --hash-done     "rt-seed-global:torrent-500k" \
                 \
                 --seeding       "rt-seed-global:torrent-100k" \
                 --seeding       "rt-seed-global:torrent-500k"

#
# Test diskspace:
#

# Verify that all relevant torrents work.
rdo_stage_rtorrent "${default_client_args[@]}" "rt-diskspace-verify-unlimited"
rdo_torrent_node   --node "rt-diskspace-verify-unlimited" "torrent-100k"
rdo_torrent_node   --node "rt-diskspace-verify-unlimited" "torrent-500k"

# Verify that default disk space limit works. (not actually testing properly as the event is scheduled)
# - Audit the 'Closed torrents due to low diskspace.' error.
# - Consider test that don't rely on scheduled timers.
rdo_stage_rtorrent "${default_client_args[@]}" --torrents-disksize "400k" "rt-diskspace-verify-500k-on-400k"
rdo_torrent_node   --node "rt-diskspace-verify-500k-on-400k" "torrent-500k"

# Verify no low disk space event leaves client running.
# rdo_stage_rtorrent "${default_client_args[@]}" --torrents-disksize "400k" "rt-diskspace-verify-500k-on-400k"
# rdo_torrent_node   --node "rt-diskspace-verify-500k-on-400k" "torrent-500k"

rdo_stage_deploy
rdo_torrent_wait --print --wait-all \
                 \
                 --completed "rt-diskspace-verify-unlimited:torrent-100k" \
                 --completed "rt-diskspace-verify-unlimited:torrent-500k" \
                 \
                 --not-completed "rt-diskspace-verify-500k-on-400k:torrent-500k"

rdo_test_end
