#!/bin/bash
#
# Missing tests:
#
#  * Add tests with throttle rather than tc.

rdo_test_begin


#
# Topology, trackers and torrents:
#

rdo_stage_network "rt-global"

rdo_stage_dns     --run-template "dns-default"     --network "rt-global" "rt-dns-global"
rdo_stage_tracker --run-template "tracker-default" --network "rt-global" "rt-tracker-global"

rdo_stage_deploy

default_client_args=(
  --run-template "rt-default"
  --network "rt-global"
  --dns-inet "rt-dns-global:rt-global"
)

#
# Seeders:
#

rdo_stage_rtorrent "${default_client_args[@]}" "rt-seed-global"

rdo_torrent_create --domain "rt-tracker-global.rt" --size-mb "1" "torrent-1m"
rdo_torrent_create --domain "rt-tracker-global.rt" --size-mb "2" "torrent-2m"
rdo_torrent_node   --seeder "rt-seed-global" "torrent-1m"
rdo_torrent_node   --seeder "rt-seed-global" "torrent-2m"

rdo_stage_deploy
rdo_torrent_wait --print --wait-all \
                 --seeding       "rt-seed-global:torrent-1m" \
                 --seeding       "rt-seed-global:torrent-2m"


#
# Test throttle:
#

test_clients=(
  "rt-priority-default"
  "rt-priority-off"
)

rdo_stage_rtorrent "${default_client_args[@]}" "${test_clients[@]}"

rdo_network_tc_replace_root_tbf --rate-epsilon "${test_clients[@]}"

rdo_stage_append_rc \
  --node "rt-priority-off" \
  'method.set_key = event.download.inserted,priority_off,{(d.priority.set,0)}'

  # 'method.set_key = event.download.inserted,priority_off,{(d.priority.set,0),(d.update_priorities)}'

  # 'method.set_key = event.download.inserted,priority_off, {(branch,((equal,(d.name),"torrent-1m")),((d.priority.set,0)))}'

rdo_torrent_node $(printf -- " --leecher %s" "${test_clients[@]}") "torrent-1m"

rdo_stage_deploy
rdo_torrent_wait --print --wait-all \
                 $(printf -- " --hash-done %s:torrent-1m" "${test_clients[@]}")

rdo_network_tc_del_root "${test_clients[@]}"

rdo_torrent_wait --print --wait-all \
                 --completed     "rt-priority-default:torrent-1m" \
                 --not-completed "rt-priority-off:torrent-1m" \

rdo_test_end
