#!/bin/bash

print_progress "staging test"
rdo_stage_init

rdo_stage_network "rt-network-1"
rdo_stage_network "rt-network-2"

rdo_stage_tracker --run-template "tracker-default" --network "rt-network-1" --network "rt-network-2" "rt-tracker-1"

rdo_stage_rtorrent --run-template "rt-default" --network "rt-network-1" "rt-seed-1"
rdo_stage_rtorrent --run-template "rt-default" --network "rt-network-1" "rt-leech-1"
rdo_stage_rtorrent --run-template "rt-default" --network "rt-network-2" "rt-leech-2"

rdo_stage_torrent --domain "rt-tracker-1.rt-network-1" "torrent-test-1"
rdo_stage_torrent --domain "rt-tracker-1.rt-network-2" "torrent-test-2"

rdo_torrent_node --node "rt-seed-1" --seed "torrent-test-1"
rdo_torrent_node --node "rt-leech-1" "torrent-test-1"
rdo_torrent_node --node "rt-leech-2" "torrent-test-2"

rdo_stage_deploy

# TODO: Add node started event.
rdo_torrent_wait --print --wait-all \
                 \
                 --hash-done "rt-seed-1:torrent-test-1" \
                 --seeding   "rt-seed-1:torrent-test-1" \
                 \
                 --hash-done     "rt-leech-1:torrent-test-1" \
                 --completed     "rt-leech-1:torrent-test-1" \
                 --not-hash-done "rt-leech-1:torrent-test-2" \
                 \
                 --not-completed "rt-leech-2:torrent-test-1" \
                 --hash-done     "rt-leech-2:torrent-test-2"

print_progress "staged test"
