#!/usr/bin/env bash

declare -A __INCLUDED_HEADERS

include_header() {
  local header_name="${1:?Missing header name argument.}"

  if [[ -n "${__INCLUDED_HEADERS[${header_name}]}" ]]; then
    echo "rdo_${header_name} already included:" >&2

    for (( i=0 ; i < ${#FUNCNAME[@]} - 1 ; i++ )); do
      echo " $i: ${BASH_SOURCE[$i+1]}:${BASH_LINENO[$i]} ${FUNCNAME[$i]}" >&2
    done

    exit 1
  fi

  __INCLUDED_HEADERS[${header_name}]="yes"
}

is_header_included() {
  local header_name="${1:?Missing header name argument.}"
  [[ -n "${__INCLUDED_HEADERS[${header_name}]}" ]]
}

include_header common
