#!/usr/bin/env bash
#
# Copyright (C) 2020 by Jari Petter Sundell <sundell.software@gmail.com>
#
# Permission to use, copy, modify, and/or distribute this software for any purpose
# with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
# OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
# THIS SOFTWARE.

include_header common/utils

utils::array_key_max_width() {
  local width=0
  local array
  for array in "${@}"; do
    declare -n array="${1:?Missing array argument.}"

    local key
    for key in "${!array[@]}"; do
      if (( ${#key} > ${width} )); then
        width=${#key}
      fi
    done
  done

  echo ${width}
}

utils::array_value_max_width() {
  local width=0
  local array
  for array in "${@}"; do
    declare -n array="${1:?Missing array argument.}"

    local value
    for value in "${array[@]}"; do
      if (( ${#value} > ${width} )); then
        width=${#value}
      fi
    done
  done

  echo ${width}
}

utils::justify_string() {
  local width="${1:?Missing width argument.}"
  local string="${2:?Missing string argument.}"

  echo -n "${string}"

  local i
  for (( i=${#string}; i < ${width}; i++ )); do
    echo -n " "
  done
}

utils::prepend_output() {
  local prepend="${@}"
  local line
  while IFS= read -r line; do
    if [[ -n "${line}" ]]; then
      echo "${prepend}${line}"
    else
      echo
    fi
  done
}
