ARG REPOSITORY
ARG TAG_APPEND


FROM "${REPOSITORY}/build/stage:${TAG_APPEND}" AS stage


FROM "${REPOSITORY}/base/run/rtorrent:${TAG_APPEND}"

WORKDIR /run/rtorrent

ENV PATH="/prefix/bin:${PATH}"

COPY --from=stage /deploy/prefix/ /prefix/
COPY bash_profile /root/.bash_profile
COPY entry-point.sh /

ENTRYPOINT /entry-point.sh rtorrent -o system.daemon.set=true
