ARG REPOSITORY
ARG TAG_APPEND


FROM "${REPOSITORY}/build/libtorrent-stage:${TAG_APPEND}" AS stage


FROM "${REPOSITORY}/build/libtorrent-base:${TAG_APPEND}"

COPY --from=stage /deploy/build/ /build/
COPY /compile/ /stage/

RUN rsync-update /stage/ /build/

RUN echo -e "\033[0;32mbuilding libtorrent\033[0m"; set -xe; \
make -j12; \
make -j12 install

RUN \
rsync-deploy-compile /build/ /deploy/build/; \
cp -rp /prefix /deploy/
