# syntax=docker/dockerfile:experimental
#
# /stage  - bind mount point for new files to add to the cache
# /deploy - the cache location to be mounted by the user of the cache

ARG REPOSITORY
ARG CACHE_BASE_TAG
ARG TAG_APPEND


FROM "${REPOSITORY}/${CACHE_BASE_TAG}" AS stage


FROM "${REPOSITORY}/cache/apk:global" AS cache


FROM "${REPOSITORY}/ancestor/cache:global"

COPY --from=stage /var/cache/apk-deploy /stage
COPY --from=cache /deploy /deploy

RUN echo -e "\033[0;32mupdating cache\033[0m"; set -xe; \
\
cd /stage; \
find . -type d -exec mkdir -v -p /deploy/{} \; ;\
find . -not -type d -exec mv -v {} /deploy/{} \;
