# syntax=docker/dockerfile:experimental

ARG REPOSITORY
ARG TAG_APPEND


FROM "${REPOSITORY}/ancestor/utils:global"

RUN \
--mount=type=tmpfs,target=/var/cache/apk \
--mount=type=bind,from=rdo/cache/apk:global,source=/deploy,target=/var/cache/apk-stage \
\
pkg-add mktorrent

CMD tail -f /dev/null
