ARG REPOSITORY
ARG TAG_APPEND


FROM "${REPOSITORY}/build/libtorrent-stage:${TAG_APPEND}" AS stage


FROM "${REPOSITORY}/build/libtorrent-base:${TAG_APPEND}"

COPY --from=stage /deploy/build/ /build/
COPY --from=stage /deploy/prefix/ /prefix/

COPY /compile/ /stage/
RUN rsync-update /stage/ /build/source/

RUN echo -e "\033[0;32mlibtorrent compile\033[0m"; set -xe; cd /build/output; \
make -j12; \
make -j12 install

RUN \
rsync-deploy-compile /build/ /deploy/build/; \
cp -rp /prefix /deploy/
