# syntax=docker/dockerfile:experimental

ARG REPOSITORY

FROM "${REPOSITORY}/ancestor:global"

WORKDIR /build

RUN \
--mount=type=tmpfs,target=/var/cache/apk \
--mount=type=bind,from=rdo/cache/apk:global,source=/deploy,target=/var/cache/apk-stage \
\
pkg-add autoconf \
        automake \
        binutils \
        file \
        libc-dev \
        libtool \
        linux-headers \
        make \
        musl-dev \
        openssl-dev \
        zlib-dev
