ARG REPOSITORY
ARG TAG_APPEND


FROM "${REPOSITORY}/build/base:${TAG_APPEND}"

COPY apk-cache/ /apk-cache/

RUN \
apk add \
    cppunit \
    cppunit-dev

ARG REPOSITORY
ARG TAG_APPEND
LABEL package_tag="ready:${REPOSITORY}/build/libtorrent-base:${TAG_APPEND}"
