# Stage recompile of rtorrent.

ARG REPOSITORY
ARG TAG_APPEND
ARG STAGE_IMAGE


FROM "${REPOSITORY}/${STAGE_IMAGE}:${TAG_APPEND}" AS stage


FROM "${REPOSITORY}/stage:${TAG_APPEND}"

COPY --from=stage /deploy /stage/
COPY --from=stage /prefix /prefix/

RUN rsync-compile-stage "/stage/*" "/deploy"
