# Stage recompile of libtorrent.

ARG REPOSITORY
ARG TAG_APPEND
ARG STAGE_IMAGE


FROM "${REPOSITORY}/${STAGE_IMAGE}:${TAG_APPEND}" AS stage


FROM "${REPOSITORY}/stage:${TAG_APPEND}"

COPY --from=stage /deploy/build/ /deploy/build/
