# syntax=docker/dockerfile:experimental
#
# /stage  - bind mount point for new files to add to the cache
# /deploy - the cache location to be mounted by the user of the cache

ARG REPOSITORY
ARG BASE_IMAGE
ARG TAG_APPEND

FROM "${REPOSITORY}/${BASE_IMAGE}:${TAG_APPEND}"

ARG REPOSITORY
ARG CACHE_FROM
ARG CACHE_SOURCE

# Argument replacement in mount option fields is not currently
# supported, use hardcoded dockerfiles for now.
RUN --mount=type=bind,from=${REPOSITORY}/${CACHE_FROM},source=${CACHE_SOURCE},target=/stage pkg-copy
