ARG REPOSITORY
ARG TAG_APPEND


FROM "${REPOSITORY}/build/libtorrent-base:${TAG_APPEND}"

COPY /configure/ /build/

RUN echo -e "\033[0;32mlibtorrent autogen.sh\033[0m"; set -xe; \
./autogen.sh

RUN echo -e "\033[0;32mlibtorrent configure\033[0m"; set -xe; \
. /env.configure; \
./configure --prefix=/prefix

RUN rsync-deploy-configure /build/ /deploy/build; \
cp -rp /prefix /deploy/
