# syntax=docker/dockerfile:experimental
#
# /stage  - bind mount point for new files to add to the cache
# /deploy - the cache location to be mounted by the user of the cache

ARG REPOSITORY
ARG BASE_IMAGE

FROM "${REPOSITORY}/${BASE_IMAGE}" AS stage

RUN --mount=type=bind,from=rdo/build/base:default,source=/var/cache/apk-deploy,target=/stage pkg-copy


FROM "${REPOSITORY}/ancestor/cache:global"

COPY --from=stage /deploy /deploy
