ARG REPOSITORY
ARG TAG_APPEND


FROM "${REPOSITORY}/build/libtorrent-base:${TAG_APPEND}"

COPY /configure/ /build/source

RUN echo -e "\033[0;32mlibtorrent autogen.sh\033[0m"; set -xe; cd /build/source; \
mkdir -p /build/output; \
./autogen.sh

RUN echo -e "\033[0;32mlibtorrent configure\033[0m"; set -xe; cd /build/output; \
. /env.configure; \
/build/source/configure --prefix=/prefix --disable-backtrace

RUN rsync-deploy-configure /build/ /deploy/build; \
cp -rp /prefix /deploy/
