ARG REPOSITORY
ARG TAG_APPEND


FROM "${REPOSITORY}/build/rtorrent-stage:${TAG_APPEND}" AS stage


FROM "${REPOSITORY}/build/rtorrent-base:${TAG_APPEND}"

COPY --from=stage /deploy/build/ /build/
COPY --from=stage /deploy/prefix/ /prefix/

COPY compile/ /stage/
RUN rsync-update /stage/ /build/

RUN echo -e "\033[0;32mcheck rtorrent\033[0m"; set -xe; \
make -j12 check

RUN \
rsync-deploy-compile /build/ /deploy/build/; \
cp -rp /prefix /deploy/
