# syntax=docker/dockerfile:experimental

ARG REPOSITORY
ARG TAG_APPEND

FROM "${REPOSITORY}/ancestor:global"

RUN \
--mount=type=tmpfs,target=/var/cache/apk \
--mount=type=bind,from=rdo/cache/apk:global,source=/deploy,target=/var/cache/apk-stage \
\
pkg-add cppunit \
        curl \
        musl \
        ncurses \
        openssl \
        zlib
