# syntax=docker/dockerfile:experimental

ARG REPOSITORY
ARG TAG_APPEND


FROM "${REPOSITORY}/ancestor/utils:alpine-3"

RUN --mount=type=cache,id=rdo-apk-cache,sharing=locked,target=/var/cache/apk/ \
  \
  apk add \
      mktorrent

CMD tail -f /dev/null
