# syntax=docker/dockerfile:experimental
#
# /stage  - bind mount point for new files to add to the cache
# /deploy - the cache location to be mounted by the user of the cache

ARG REPOSITORY
ARG BASE_IMAGE

FROM "${REPOSITORY}/${BASE_IMAGE}"

RUN --mount=type=bind,from=rdo/ancestor:default,source=/var/cache/apk-deploy,target=/stage \
\
cd stage; \
\
find . -type d -exec mkdir -p "/deploy/{}" \; ;\
find . -not -type d -exec cp -ap "{}" "/deploy/{}" \;
