ARG REPOSITORY
ARG TAG_APPEND


FROM "${REPOSITORY}/build/base:${TAG_APPEND}"

COPY apk-cache /apk-cache

RUN \
apk add \
    cppunit \
    cppunit-dev \
    curl-dev \
    ncurses-dev

ARG REPOSITORY
ARG TAG_APPEND
LABEL package_tag="ready:${REPOSITORY}/build/rtorrent-base:${TAG_APPEND}"
