# syntax=docker/dockerfile:experimental
#
# An ancestor image for various cache images. Each cache has a
# different ancestor label to allow the deletion of all project
# related images without removing e.g. the package cache.
#
# /stage  - bind mount point for new files to add to the cache
# /deploy - the cache location to be mounted by the user of the cache

FROM "alpine"

ARG ANCESTOR_PROJECT

LABEL ancestor_project="${ANCESTOR_PROJECT}"

RUN mkdir -p /deploy /stage

COPY bin/pkg-copy /usr/bin/
