# Stage recompile of rtorrent.

ARG REPOSITORY
ARG TAG_APPEND
ARG STAGE_IMAGE


FROM "${REPOSITORY}/${STAGE_IMAGE}:${TAG_APPEND}" AS stage


FROM "${REPOSITORY}/build/rtorrent-base:${TAG_APPEND}"

COPY --from=stage /deploy/build/ /deploy/build/
COPY --from=stage /deploy/prefix/ /deploy/prefix/
