# An ancestor image for various cache images. Each cache has a
# different ancestor label to allow the deletion of all project
# related images without removing e.g. the package cache.
#
# /stage  - bind mount point for new files to add to the cache
# /deploy - the cache location to be mounted by the user of the cache

FROM "alpine"

ARG ANCESTOR_PROJECT

LABEL ancestor_project="${ANCESTOR_PROJECT}"

ENV RDO_RSYNC_ADD_ARGS="-rlpgoD -muc -t"
ENV RDO_RSYNC_UPDATE_ARGS="-rlpgoD -muc -t --delete-after"
ENV RDO_TIMESTAMP_UPDATE="touch /timestamp; sleep 1.1"
ENV RDO_TIMESTAMP_PATH="/timestamp"

RUN mkdir -p /deploy /stage

COPY /bin/pkg-copy /bin/rdo-find-move /usr/bin/
