# syntax=docker/dockerfile:experimental

ARG REPOSITORY
ARG TAG_APPEND

FROM "${REPOSITORY}/build/libtorrent/stage:${TAG_APPEND}"

RUN \
--mount=type=bind,from=rdo/build/libtorrent/compile:default,source=/deploy/output,target=/stage/output \
--mount=type=bind,from=rdo/build/libtorrent/compile:default,source=/deploy/source,target=/stage/source \
set -xe; \
\
rsync -rlpgoD -muc --delete-after /stage/output/ /deploy/output/; \
rsync -rlpgoD -muc --delete-after /stage/source/ /deploy/source/
