# syntax=docker/dockerfile:experimental

FROM "lednerb/opentracker-docker"

WORKDIR /run/self

RUN --mount=type=cache,id=rdo-apk-cache,sharing=locked,target=/var/cache/apk/ \
  \
  apk add \
      bash

COPY bash_profile /root/.bash_profile
COPY entrypoint.sh /

LABEL ancestor_project_root="rdo"
LABEL ancestor_project="run"

ENTRYPOINT /entrypoint.sh
