FROM alpine:latest

RUN echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

RUN apk add --no-cache bash bind-tools coredns@testing

EXPOSE 53/tcp 53/udp

COPY bash_profile /root/.bash_profile
COPY entrypoint.sh /

LABEL ancestor_project_root="rdo"
LABEL ancestor_project="run"

ENTRYPOINT /entrypoint.sh
