FROM alpine:latest

RUN apk add --no-cache bash bind

EXPOSE 53/tcp 53/udp

VOLUME ["/etc/bind", "/var/lib/bind"]

COPY bash_profile /root/.bash_profile
COPY entrypoint.sh /

LABEL ancestor_project_root="rdo"
LABEL ancestor_project="run"

ENTRYPOINT /entrypoint.sh
